# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 259ce071efc1e618be4e2f3ec5bd3179fb5fa4956df45965399fcffa7ed72a49eaa9ead6ae633130e6ffddca11a9ab85b01863dce128e460af1197135ee1260f

test:
  secret_key_base: cf3f99ded5b8a962e9930813ebfd59fa6b66c985b382ea933739904c08ec816581a145433ca81e5da2ad6bdf98267612933b3597e3436f0dc519e0c8748d662c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
